# Configuration for the External Price API crate

[external_price_api_client]

# What source to use for the external price API. Currently only options are "forced", "no-op", and "coingecko".
source = "forced"
forced_numerator = 6
forced_denominator = 5
